# Generated by Django 4.2.4 on 2023-09-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IndividualPrasprint", "0002_rename_teacher_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="person",
        ),
    ]
